import FluentSQL
import Vapor

struct LatestEntriesMigration: Migration {
  func prepare(on database: Database) -> EventLoopFuture<Void> {
    guard let sql = database as? SQLDatabase else {
      return database.eventLoop.makeFailedFuture(InvalidDatabaseError())
    }

    return sql.raw("""
      -- DDL generated by Postico 1.5.14
      -- Not all database features are supported. Do not use for backup.

      -- Table Definition ----------------------------------------------

      CREATE VIEW latest_entries AS  SELECT latest.id,
          latest.channel_id
         FROM ( SELECT DISTINCT ON (entries.channel_id) entries.id,
                  entries.channel_id,
                  entries.feed_id,
                  entries.title,
                  entries.summary,
                  entries.content,
                  entries.url,
                  entries.image,
                  entries.published_at,
                  entries.created_at,
                  entries.updated_at
                 FROM entries
                ORDER BY entries.channel_id, entries.published_at DESC) latest
        ORDER BY latest.published_at DESC;

      """
    ).run()
  }

  func revert(on database: Database) -> EventLoopFuture<Void> {
    guard let sql = database as? SQLDatabase else {
      return database.eventLoop.makeFailedFuture(InvalidDatabaseError())
    }
    return sql.raw("drop view if exists latest_entries").run()
  }
}
