name: Documentation

on:
  push:
    branches: [main]

jobs:
  swift-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@1.0.0-beta.5
        with:
          inputs: "Sources"
          module-name: XMLCoder
          format: html
          base-url: "/XMLCoder"
          output: ./.build/documentation
      - run: sudo chmod o+r -R ./.build/documentation
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/documentation
