#if !canImport(ObjectiveC)
  import XCTest

  extension OrchardNestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrchardNestTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(OrchardNestTests.__allTests__OrchardNestTests)
    ]
  }
#endif
